// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG3FcNqca6Qv3bJG2wuW_5khAXT4P87Jo',
    appId: '1:401504900993:web:8bd59fa18a3674595e7a80',
    messagingSenderId: '401504900993',
    projectId: 'mynotes-sumit-flutter',
    authDomain: 'mynotes-sumit-flutter.firebaseapp.com',
    storageBucket: 'mynotes-sumit-flutter.appspot.com',
    measurementId: 'G-SKPWQF63MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfZ7_7eCCeFUWiMXCX9q15qBh1_r1qqo',
    appId: '1:401504900993:android:4c6c25de4b04d10e5e7a80',
    messagingSenderId: '401504900993',
    projectId: 'mynotes-sumit-flutter',
    storageBucket: 'mynotes-sumit-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrCVg_QaW69lmIADKuFs25HSlIWzgBN8',
    appId: '1:401504900993:ios:1e3bf9a82add88135e7a80',
    messagingSenderId: '401504900993',
    projectId: 'mynotes-sumit-flutter',
    storageBucket: 'mynotes-sumit-flutter.appspot.com',
    iosClientId: '401504900993-kdi5ea95bo7ufqkgbiqg4ql2k2ni7f1b.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDrCVg_QaW69lmIADKuFs25HSlIWzgBN8',
    appId: '1:401504900993:ios:1e3bf9a82add88135e7a80',
    messagingSenderId: '401504900993',
    projectId: 'mynotes-sumit-flutter',
    storageBucket: 'mynotes-sumit-flutter.appspot.com',
    iosClientId: '401504900993-kdi5ea95bo7ufqkgbiqg4ql2k2ni7f1b.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.mynotes',
  );
}
